spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amanangular13/hotel-config-repo
          default-label: main

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true